language: android
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_29be1e4c0605_key -iv $encrypted_29be1e4c0605_iv -in easysense/release-key.keystore.enc -out easysense/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
script:
- "./gradlew assembleRelease"
notifications:
  slack:
    secure: drSaLEsi+xlUePocfcDTLO9S/5XSBsnR6h7OzPhU4xsO+mBjH3qb93Qe4Jwzz9IZQ0UFzDcmu7ObHOksd6fDgvnIcmznowuABs7QFSF5dodF3eXuF/NJc5J3SqptrOZhlPhGQJcan8siBpLw5z+UBal9ORQPJ8e0SN2bxvRH30GzOlaBOrS0w9hGmtoIY/c8ZIjxGn7BK+b7qL6pNqD4tTg3BImh4Q8Q0icjlT/Pe4kq9pJuYP+Ph4B6THE5PY6W5kmaPSZT2wk72tbNa+1f0lxkO106+Fi4X/qEf6BNQ/2ufUi8cGyjYhu8ZRfGEQVwmwtk0goZvPRyxzHx94tc0/utmW+ZvEEdXOTfs1cE84xGvsYOmoMaMacJC0DPSRTJ269LnmUlTYZoZPyEaqEJp0vFLnS7ZwYcYBzEQ/coS1zKOEWX5a29ijvCOxeFGWF9NcEvaGfpoP/RiLJXjguKfrQLQiek+xkzmubSRWpP9LFoqtXwVMxle/zi/99Ry02nvmEUSK3BbAM57LBnrT+0lYDC/ocxTpQ3Gvd52qFoZBzb8Fshu2+3UYCSCHROkOdHtBmBvRKE4LiTz8/6xtzeL1n+1RSrbN13tbk01gkNIHagSLWUildtFkvok2pJXawslE88ZhRzOOK8ViWFenbhca6sPfvBebXccTJKnzi4GQc=
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: aseFwQ9GftZeMdTfie4zlWi9MBMOxvur4h4q4BC7SvOD31c2XoppKSxYdNznkIW/ZckNVwXjFrex4BIT1Cx5ETU4fTz3o/x9/ispkeBTAgYQ+PoZIgIAQxNoNopq/z+ZgelKwlHytdTfioEm+CtJUbhFuW1UDtb2wBS5h9Y+a5XuuOiLgjjrgAhu7W/YX0nx3LYSc+r/jWJ9LXllBzgDo6gSZNvRN1wWljnAIfFsnotvxBMuj8jXxQdh2fHZmLaQaTZWQKsz0vBI6oo7FX1qDwELbq4mLApWpAtDcL1wyFXpio8z0cCl2h3k/+QthgH0w/GRZFo1+ubnnuKod2M7TKNVin62oysJRZf6fLzbSGIam6op3XPEkIrtXD1WYd+hYlN3U6BrtB7hgzqa1MblGLiaUnqWs/cWW/CUV2AkHuTVRTv2nonDWn60iTk1oXD2whqtup4mjZ/VBEvdEvrGCtPJZ7DeO9sT0iPZH7j5CYdWB/XYJDktlIwraWe7wt3YkRLmBQwu1bdJJvof+N3IfNcvLpPahEK47T8VL/ln7iAWb0lHFniKcrXk8V/Yx6VaYrhY7KnLBTn0GRlbpXyrMz1LfSvUpuuLV8a66tdkJXD1OyoiN/HD6BqyVxHpYmshrAgchL1AX3srpu8PwZMxs58+i9mJwOdvnX2v3+H29ko=
  - secure: iT4b84WILv3X16xSPG0hzv52DeJdNQu5VNBU9myeFoaQ/+q8eW35QVfpMRUM0380sFPYECL6b2r3A5cWzeOK1iBBqcMuqtbYgnH5Mk3l/PIpwvTVY3eyV8mYA1xz42cTq0U/H9EnGOvDwK0tTJvSSMRxKOmUVaL+RuU/80PainBf0k9LYxLPkhmG6JHEofKIXDRNlL2+vBqyjxxEi06OTxM6K2PzzqogCQtY1VnRrr8NUynkOM0EkE+80w9PmKLV/fz07O6/JqZjgaIQWZIBjPI14Eb26BYZvXfn4tRC/Xf7D6T74nLjT21cAKDjUQWSIJRqPXdBh+K6rjhkQcqMoLeeydaKGOiyENebgpMgHu4jKlqrtO2M9roktlGaZ+DU9jA/Qnrc2i+340zznH3b8p8xApwJtFWKPcyxfOBExohlZE+cbbusvZmioum41ZYgnhDSxcGh8Q76ibILSuflYriBIAXZlUowyjgtThCM4k7FrhkhVXQKpVpgvSTz/1eIlxNHGrMrN+1CN1E0nPqAWObF5fLSDhZNnhFMWAblXxkHkh/9IPMx7pfkGS+ZpSdd+7q/eHbe10XqGcNXO80Xps1yWaH9wYAbQpij2Wy+zEgGLyk0g4HlDLJ+SPTDUV818p1z4LuUEAX1RNn9XSCwJcJO5ZRU18XoLlM01ZaMn14=
  - secure: az4wC3hkpje5+uPfvzvve2FbzN3nG42HNHUzd4XJTQMSYBGYQjMZ4K+7uqomW3RMPq1FW6X6f72j/dsHQA/WUT/nXE4LYBvSQn6MLYnTwgDyjvPd54ceNn3RgEF39556dK6t5GnWAyjz47FbBUPgBRp81t3pudASe3ZkxWjkfI5oyHaTAVZFWBWIP3GAvWxbWz53JhMflG724NeelxjELQ7Qc7sV3baDQWFknQjBH4JehvkgxS/EGxaqoKX9VFyq9owObgv++YjZQ/koog8WCX7B3jb/RV3SKjTimjLlKEfHPv3M5pyIgpBAb5NNUswjbmUu1vUnmF2KYUA9ANGsFvARPRqqsU0zOZbsrI4rHoTE1k2g27gqrEjEyPmgtnMsBKkYpVHcfKXxPm3+CbZllJUdV0nbFk7HIHQD9ZjwT9mbxTV4OpyBXQExpKq06p3dtd4tQ7vxDP8aD3XePa87DCoITHe1rtbiSmq1Pqq/UP3mjgahV+3/ohQ30beLUIfbeGrBwQYRIMCYXKCnsI2e2aznBTPr1hZwgJSWB0iYQyUnjqLE8gKCUY76u68pld6WQDQL/gbEy4KPw/E3VJRNoIUnROx/33lIzqV2VtdDf2WoBu70m/SAEBWTtSiO85Q4YLxn26T6PEDa+oqYHWHMquFqM7IJce9M+BOw0GfOvy0=
  - secure: qjLjEV1hBlj9DH221d81mMOcupeqkUB4Y8U1a+eH9hZgKKsFLc6Nu68qjRcINRzIH9VZVLLhVJHX4aaiCrlpw/V1lTNRnvdx1Ky2LlUkg9bORC7rWmONFOX2G/po2hOjJn9OgnHghLmEbLp4vKoxGvzdHo4POXTm83b+I2KIcsryl7EPrM+WAnYFww5uoY+eqU+SDkCI2Wt4OTbIZ72Iaqjn4exRSw8o5AwYNGV3c/ixh4GSV8kI+aYY810NrXaeYqU6k0ex9d9NaM+X1Vi0vepy93zRht2rF40jkLsrVvFylVglgs1DpCbzK1MifYYMJChMoFpTWLGxKC+4/Ixw49yJK8m9grp+a4dACdxZYdhCgXRuLrw40G7EYg2VvmeTDlBXo6LXczEl8h0SA/3q7ggl3Cs9OU1pmZd0ErNBm6ZqQXLRJHXSERKNSaLqJnStjYWHJ2b+mr3MOjnkS+D7mfqhgARaCvl4zrjVRaVSzyVAlYY6eSYPYGn2NM1onTGxj+WFZMMtxflUqhUfINZoS5yGbJFW4Q9uhgTXcrXIN9LjfvSLDZcdSY6OXIfxRrR8YiuYLc7000WeResvIwDpktrFCGzoxFORh7z4gcAL+s7jZLqT1dc0yEu5Hj/TG2axBTCO2I2OFwMgIWRew9iwhU2qdok44rMyz/aL5KW1G88=
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: e2onr4XZPzuG5DdGwiDeY8sA3bMKljX+lxqyw2KQRR7MG1lRC6X+F2Xwth49Gl3e0qaLJKMVycjAprP4qVkcSZSrcBEuZx70l1hJXgWh1yE13+67OV9e3gPw+V5DMUEaC9t25jHo6m9fADXhZK1p6pwuVut2fkg1akOZikbBjSBXw1fnBmAwAkCGRQo1lw0rG4VKap4hQ+k6iFWXbxeDPTXJGLNCD9XgQYRylD1aZiprEp/9J8AVtJn4Br1kw6HZJAP+BbYAluM9MBLc6d58oKOeIHASITdDWEe6nhS/AiHmpmjGbRC+QpBUK3PClJJLMmpYTHtVG1yNTtKiYVi8NfHllqLjNDBF5Ape52Pl9fSzq6ZF6DEY6zwV4n521yt7O1bYZq37mpli/xTzvhBQKCOBgOeo7WdzJSQTlDo7OoYUsoplRfvx646glJbpm3pqYkql9iR+vl7E+j7ZRXE5CE79e9RsetwS5KGvGfawVtrbFRr2tPxwzf5XDcBA8lv4865ITHtdh3mqYt63Rq2hzSY+MyFPo3dgM5/zpazY+/3oJc6aPGXp23wTqDDUu3z1pZwm3bjzsmC1b5gK/xBpWL0q5i+BolpfvImlA8rCxQ0/YESIrN9UqukIYrkbdd1pAFNud4m/OSBiyvBlg+l38JelUTs2Xn+a6YsUeni5v/Q=
  file: easysense/build/outputs/apk/easysense*.*.*.apk
  on:
    repo: MD2Korg/mCerebrum-EasySense
    tags: true
  skip_cleanup: true
